config/routes.rb
Bueller::Application.routes.draw do
 
  

 
  resources :students
  
  resources :posts
    root to: "welcome#index"
 

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 
  def new
  end
  
  def index    
  end
  
  def create
    @student = Student.new(params[:student].permit(:name, :nickname, :email, :gravatar))
    if ( @student.gravatar.length == 0 )

        require 'digest/md5'
       email_address = @student.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        @student.gravatar = "http://www.gravatar.com/avatar/#{hash}"
         
    end
    @student.save
    if( @student.save )
      flash[:notice] = "You have succesfully created a student!"
      redirect_to @student, :flash => { :notice => "The student was successfully created!" }
    end
  end
  
  def edit
    @student = Student.find(params[:id])
  end
  
  def destroy
  end
  
  def update
     @student = Student.find(params[:id])
    if @student.update(params[:student].permit(:name, :nickname, :email, :gravatar))
      @student.save
      redirect_to @student, :flash => { :notice => "You successfully updated your student profile!" }
     
    else
        render 'edit'
    end   
   
  end
  
  def show
    @student = Student.find(params[:id])
    redirect_to :root
  end
  
  private
  def student_params
    params.require(:student.permit(:name, :nickname, :email, :gravatar))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @students = Student.all
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/students/_form.html.erb
<h1 style = "color:red;"> Update Student </h1>
<br>

<%= form_for :student, url: student_path(@student), method: :patch do |f| %>

  <p>  
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.label :gravatar %>
    <%= f.text_field :gravatar %>
   
  </p>

  <p>
    <%= f.submit "Edit student" %>
  </p>
<% end %>
<%= link_to 'Back', root_path %>  

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
  <h1 style = "color:red;"> Create New Student </h1>
<br>

<%= form_for :student, url: students_path do |f| %>
  
   <p>  
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br>
    <%= f.label :gravatar %>
    <%= f.text_field :gravatar %>
  </p>

  <p>
    <%= f.submit "Create student" %>
  </p>
<% end %>
<%= link_to 'Back', root_path %>  

app/views/welcome/index.html.erb
<h1 style = "color:red;"> Welcome to Bueler! </h1>
<p> <%= link_to 'New Student', students_path %></p>


<% if flash[:notice] -%>
  <p class='notice'><%=h flash[:notice] %></p>
<% end -%>

<table border="2px">
  <tr>
     <th>Name</th>
     <th>Nickname</th>
      <th>Email</th>
      <th>Gravatar Image</th>
      <th>Options</th>
  </tr>
  <% @students.each do |s| %>
  <tr >
      <td width="15%" style = "text-align:center;"><%= s.name %> </td>
      <td width="15%" style = "text-align:center;"><%= s.nickname %>  </td>
      <td width="20%" style = "text-align:center;"><%= s.email %> </td>&nbsp;&nbsp;&nbsp;&nbsp;
      <td width="20%" style = "text-align:center;"><img src = <%= s.gravatar %> height="100" width="100"> </td>
      <td width="5%" style = "text-align:center;"><%= link_to 'Edit', edit_student_path(s) %> </td>
    </tr>
  <% end %>
  
  
</table>